### ISSUE TITLE
Fail to import template

### ISSUE THREAD

**Issue by raafcioo** [RobinR1/zbx-template-yum-updateinfo#2]
Hey,
I have a problem. 
I cant import file with template to zabbix.

Failed: "Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "triggers"."

My zabbix version: Zabbix 5.0.10
I was try to fix file xml but unsuccessfully.

Thank you in advance for any help!

**Comment by RobinR1** [comment]
Strange. This should be supported since v4.2. 
Granted, the template is said to be 4.0 compatible, but 4.0 does not yet support a triggers tag inside an item tag.. so this is actually a problem there. I will look into this. But importing it in 5.0.10 should actually not pose any problems

**Comment by RobinR1** [comment]
@raafcioo, Could you try importing [this version](https://github.com/RobinR1/zbx-template-yum-updateinfo/blob/487888737d7b16e5a5cb45de222cc09c5e9794e1/template_module_yum_updateinfo-4.0.xml) of the template?

**Comment by raafcioo** [comment]
@RobinR1 Full success. Everything works. Thanks for help :)

**Comment by RobinR1** [comment]
Fixed in 487888737d7b16e5a5cb45de222cc09c5e9794e1
